/**
 * Generate a test .apkg file that can be imported into Anki to verify correctness.
 * Run with: bun run test/generate-test-deck.ts
 */
import initSqlJs from "sql.js";
import { Package, Deck, DeckConfig, Model, Note } from "../src/index";

const SQL = await initSqlJs();

// FSRS config optimized for a 4-day sprint
const config = new DeckConfig({
  name: "ankipack Test FSRS",
  desiredRetention: 0.95,
  learnSteps: [1, 10],
  relearnSteps: [10],
  newPerDay: 50,
  reviewsPerDay: 9999,
  maximumReviewInterval: 4,
  buryNew: true,
  buryReviews: true,
  buryInterdayLearning: true,
  newCardGatherPriority: "deck",
  newCardSortOrder: "noSort",
  reviewOrder: "retrievabilityAscending",
});

// Custom model with recognition + typing
const vocabModel = new Model({
  name: "Vocab (Recognition)",
  fields: [{ name: "French" }, { name: "German" }],
  templates: [
    {
      name: "Recognition",
      questionFormat: '<div style="font-size: 28px;">{{French}}</div>',
      answerFormat:
        '<div style="font-size: 28px;">{{French}}</div>\n\n<hr id="answer">\n\n<div style="font-size: 24px;">{{German}}</div>',
    },
  ],
});

const typingModel = new Model({
  name: "Vocab (Typing)",
  fields: [{ name: "German" }, { name: "French" }],
  templates: [
    {
      name: "Type French",
      questionFormat:
        '<div style="font-size: 24px;">{{German}}</div>\n\n<br>\n\n{{type:French}}',
      answerFormat: '<div style="font-size: 24px;">{{German}}</div>\n\n<hr id="answer">\n\n{{type:French}}',
    },
  ],
});

// Build deck
const deck = new Deck({
  name: "ankipack Test Deck",
  description: "Generated by ankipack to verify .apkg import",
  config,
});

// Sample words
const words = [
  ["l'animal, les animaux", "das Tier, die Tiere"],
  ["la vache", "die Kuh"],
  ["le chien", "der Hund"],
  ["le chat", "die Katze"],
  ["la plante", "die Pflanze"],
  ["l'arbre", "der Baum"],
  ["la mer", "das Meer"],
  ["le soleil", "die Sonne"],
  ["la pluie", "der Regen"],
  ["le vent", "der Wind"],
];

for (const [french, german] of words) {
  deck.addNote(
    new Note({
      model: vocabModel,
      fields: [french, german],
      tags: ["test", "french"],
    }),
  );
  deck.addNote(
    new Note({
      model: typingModel,
      fields: [german, french],
      tags: ["test", "french", "typing"],
    }),
  );
}

// Also add a cloze card to test that
const clozeModel = Model.cloze();
const clozeDeck = new Deck({ name: "ankipack Test Deck::Cloze" });
clozeDeck.addNote(
  new Note({
    model: clozeModel,
    fields: [
      "{{c1::Paris}} is the capital of {{c2::France}}",
      "Geography fact",
    ],
  }),
);

const pkg = new Package();
pkg.addDeck(deck);
pkg.addDeck(clozeDeck);

const outPath = new URL("../../tmp/test-output.apkg", import.meta.url).pathname;
await pkg.writeToFile(outPath, SQL);

console.log(`Generated: ${outPath}`);
console.log(`  Decks: 2`);
console.log(`  Notes: ${words.length * 2 + 1} (${words.length} recognition + ${words.length} typing + 1 cloze)`);
console.log(`  Cards: ${words.length * 2 + 2} (cloze has 2 cards: c1, c2)`);
console.log(`\nImport into Anki to verify. After import:`);
console.log(`  1. Enable FSRS in Deck Options`);
console.log(`  2. Check that "ankipack Test FSRS" preset exists`);
console.log(`  3. Verify desired retention = 0.95`);
console.log(`  4. Verify max interval = 4 days`);
