import { describe, test, expect } from "bun:test";
import { Notetype, Note, Deck, DeckConfig, Package } from "../src/index";
import { openPackage, scalar } from "./helpers/collection";

// Anki's empty-card rule, case by case. The oracle is Anki itself:
// `template_is_empty` in rslib/src/template.rs and `is_nonempty` in
// rslib/src/notetype/cardgen.rs. Each case runs end to end and counts cards,
// so it covers card generation rather than just the template walker.

/**
 * Cards generated by the note type's own templates. A control template that
 * always renders is prepended, because Anki's `ensure_not_empty` forces card 0
 * when nothing renders, which would make "renders" and "does not render"
 * indistinguishable on a single-template note type.
 */
async function countCards(notetype: Notetype, fieldValues: string[][]): Promise<number> {
  const withControl = new Notetype({
    name: notetype.name,
    type: notetype.type,
    fields: [{ name: "Control" }, ...notetype.fields],
    templates: [
      { name: "Control", questionFormat: "{{Control}}", answerFormat: "x" },
      ...notetype.templates,
    ],
  });

  const deck = new Deck({
    name: "test-deck",
    config: new DeckConfig({ name: "test-config" }),
  });
  for (const fields of fieldValues) {
    deck.addNote(new Note({ notetype: withControl, fields: ["always", ...fields] }));
  }
  const pkg = new Package();
  pkg.addDeck(deck);

  const opened = await openPackage(pkg);
  try {
    return Number(scalar(opened.db, "SELECT COUNT(*) FROM cards WHERE ord > 0"));
  } finally {
    opened.db.close();
  }
}

const FIELDS = [
  { name: "Term" },
  { name: "Definition" },
  { name: "TermImage" },
  { name: "TermAudio" },
  { name: "TermTTS" },
  { name: "DefinitionImage" },
  { name: "DefinitionAudio" },
  { name: "DefinitionTTS" },
  { name: "AddReverse" },
];

describe("empty-card rule, end to end", () => {
  test("plain text alone is treated as empty (no card)", async () => {
    const notetype = new Notetype({
      name: "plain-text-only",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "<p>Hello world (no field references)</p>",
          answerFormat: "{{FrontSide}}{{Definition}}",
        },
      ],
    });
    const cards = await countCards(notetype, [["Term-A", "Def-A", "", "", "", "", "", "", ""]]);
    expect(cards).toBe(0);
  });

  test("a single non-empty replacement makes the card non-empty", async () => {
    const notetype = new Notetype({
      name: "single-ref",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "{{Term}}",
          answerFormat: "{{Definition}}",
        },
      ],
    });
    expect(await countCards(notetype, [["Term-A", "", "", "", "", "", "", "", ""]])).toBe(1);
    expect(await countCards(notetype, [["", "", "", "", "", "", "", "", ""]])).toBe(0);
  });

  test("section with empty gate suppresses entire body, even if inner refs are non-empty", async () => {
    // A section gate is evaluated before its body, so a non-empty field inside
    // a gate whose own field is empty does not make the card render.
    const notetype = new Notetype({
      name: "gated-section",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "{{#Definition}}<div>{{Term}}</div>{{type:Definition}}{{/Definition}}",
          answerFormat: "{{FrontSide}}",
        },
      ],
    });
    expect(await countCards(notetype, [["Argentina", "", "", "", "", "", "", "", ""]])).toBe(0);
    expect(await countCards(notetype, [["Argentina", "country", "", "", "", "", "", "", ""]])).toBe(
      1,
    );
  });

  test("nested sections evaluate inner gate too", async () => {
    const notetype = new Notetype({
      name: "nested",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "{{#AddReverse}}{{#Term}}<div>{{Term}}</div>{{/Term}}{{/AddReverse}}",
          answerFormat: "{{FrontSide}}",
        },
      ],
    });
    // outer gate empty
    expect(await countCards(notetype, [["x", "", "", "", "", "", "", "", ""]])).toBe(0);
    // outer gate set, inner ref non-empty
    expect(await countCards(notetype, [["x", "", "", "", "", "", "", "", "1"]])).toBe(1);
    // outer gate set, inner ref empty
    expect(await countCards(notetype, [["", "", "", "", "", "", "", "", "1"]])).toBe(0);
  });

  test("negated section: shows when field is empty", async () => {
    // A negated body is only walked when its gate is empty, so filling the gate
    // leaves no reachable replacement at all.
    const notetype = new Notetype({
      name: "negated",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "{{^Definition}}{{Term}}{{/Definition}}",
          answerFormat: "{{FrontSide}}",
        },
      ],
    });
    expect(await countCards(notetype, [["Argentina", "", "", "", "", "", "", "", ""]])).toBe(1);
    expect(await countCards(notetype, [["Argentina", "country", "", "", "", "", "", "", ""]])).toBe(
      0,
    );
  });

  test("{{type:Field}} is treated as a Replacement on the underlying field", async () => {
    const notetype = new Notetype({
      name: "type-filter",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "Type: {{type:Definition}}",
          answerFormat: "{{FrontSide}}",
        },
      ],
    });
    expect(await countCards(notetype, [["x", "", "", "", "", "", "", "", ""]])).toBe(0);
    expect(await countCards(notetype, [["x", "answer", "", "", "", "", "", "", ""]])).toBe(1);
  });

  test('field with only "<br>" or "<div></div>" counts as empty', async () => {
    const notetype = new Notetype({
      name: "br-only",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "{{Term}}",
          answerFormat: "{{FrontSide}}",
        },
      ],
    });
    expect(await countCards(notetype, [["<br>", "", "", "", "", "", "", "", ""]])).toBe(0);
    expect(await countCards(notetype, [["<div></div>", "", "", "", "", "", "", "", ""]])).toBe(0);
    expect(await countCards(notetype, [["  ", "", "", "", "", "", "", "", ""]])).toBe(0);
    expect(await countCards(notetype, [["<div>x</div>", "", "", "", "", "", "", "", ""]])).toBe(1);
  });

  test("{{FrontSide}} alone does not make the question non-empty", async () => {
    // FrontSide is special; it's never in the nonempty_fields set.
    const notetype = new Notetype({
      name: "frontside-only",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "{{FrontSide}}",
          answerFormat: "{{FrontSide}}",
        },
      ],
    });
    expect(await countCards(notetype, [["x", "y", "", "", "", "", "", "", ""]])).toBe(0);
  });
});
