import { describe, test, expect } from "bun:test";
import { Model, Note, Deck, DeckConfig, Package } from "../src/index";
import { openPackage, scalar } from "./helpers/collection";

// Anki's empty-card rule, case by case. The oracle is Anki itself:
// `template_is_empty` in rslib/src/template.rs and `is_nonempty` in
// rslib/src/notetype/cardgen.rs. Each case runs end to end and counts cards,
// so it covers card generation rather than just the template walker.

/**
 * Cards generated by the model's own templates. A control template that always
 * renders is prepended, because Anki's `ensure_not_empty` forces card 0 when
 * nothing renders, which would make "renders" and "does not render"
 * indistinguishable on a single-template model.
 */
async function countCards(model: Model, fieldValues: string[][]): Promise<number> {
  const withControl = new Model({
    name: model.name,
    type: model.type,
    fields: [{ name: "Control" }, ...model.fields],
    templates: [
      { name: "Control", questionFormat: "{{Control}}", answerFormat: "x" },
      ...model.templates,
    ],
  });

  const deck = new Deck({
    name: "test-deck",
    config: new DeckConfig({ name: "test-config" }),
  });
  for (const fields of fieldValues) {
    deck.addNote(new Note({ model: withControl, fields: ["always", ...fields] }));
  }
  const pkg = new Package();
  pkg.addDeck(deck);

  const opened = await openPackage(pkg);
  try {
    return Number(scalar(opened.db, "SELECT COUNT(*) FROM cards WHERE ord > 0"));
  } finally {
    opened.db.close();
  }
}

const FIELDS = [
  { name: "Term" },
  { name: "Definition" },
  { name: "TermImage" },
  { name: "TermAudio" },
  { name: "TermTTS" },
  { name: "DefinitionImage" },
  { name: "DefinitionAudio" },
  { name: "DefinitionTTS" },
  { name: "AddReverse" },
];

describe("empty-card rule, end to end", () => {
  test("plain text alone is treated as empty (no card)", async () => {
    const model = new Model({
      name: "plain-text-only",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "<p>Hello world (no field references)</p>",
          answerFormat: "{{FrontSide}}{{Definition}}",
        },
      ],
    });
    const cards = await countCards(model, [["Term-A", "Def-A", "", "", "", "", "", "", ""]]);
    expect(cards).toBe(0);
  });

  test("a single non-empty replacement makes the card non-empty", async () => {
    const model = new Model({
      name: "single-ref",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "{{Term}}",
          answerFormat: "{{Definition}}",
        },
      ],
    });
    expect(await countCards(model, [["Term-A", "", "", "", "", "", "", "", ""]])).toBe(1);
    expect(await countCards(model, [["", "", "", "", "", "", "", "", ""]])).toBe(0);
  });

  test("section with empty gate suppresses entire body, even if inner refs are non-empty", async () => {
    // The KEY case for our typing card: {{#Definition}}...{{Term}}...{{/Definition}}
    // With Definition="" and Term="Argentina", the card must NOT generate.
    const model = new Model({
      name: "gated-section",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "{{#Definition}}<div>{{Term}}</div>{{type:Definition}}{{/Definition}}",
          answerFormat: "{{FrontSide}}",
        },
      ],
    });
    // Definition empty → card not generated even though Term is non-empty
    expect(await countCards(model, [["Argentina", "", "", "", "", "", "", "", ""]])).toBe(0);
    // Definition non-empty → card generates
    expect(await countCards(model, [["Argentina", "country", "", "", "", "", "", "", ""]])).toBe(1);
  });

  test("nested sections evaluate inner gate too", async () => {
    const model = new Model({
      name: "nested",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "{{#AddReverse}}{{#Term}}<div>{{Term}}</div>{{/Term}}{{/AddReverse}}",
          answerFormat: "{{FrontSide}}",
        },
      ],
    });
    // outer gate empty
    expect(await countCards(model, [["x", "", "", "", "", "", "", "", ""]])).toBe(0);
    // outer gate set, inner ref non-empty
    expect(await countCards(model, [["x", "", "", "", "", "", "", "", "1"]])).toBe(1);
    // outer gate set, inner ref empty
    expect(await countCards(model, [["", "", "", "", "", "", "", "", "1"]])).toBe(0);
  });

  test("negated section: shows when field is empty", async () => {
    const model = new Model({
      name: "negated",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "{{^Definition}}{{Term}}{{/Definition}}",
          answerFormat: "{{FrontSide}}",
        },
      ],
    });
    // Definition empty → negated body active → Term ref counts → renders
    expect(await countCards(model, [["Argentina", "", "", "", "", "", "", "", ""]])).toBe(1);
    // Definition non-empty → negated body skipped → no replacement reachable → empty
    expect(await countCards(model, [["Argentina", "country", "", "", "", "", "", "", ""]])).toBe(0);
  });

  test("{{type:Field}} is treated as a Replacement on the underlying field", async () => {
    const model = new Model({
      name: "type-filter",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "Type: {{type:Definition}}",
          answerFormat: "{{FrontSide}}",
        },
      ],
    });
    expect(await countCards(model, [["x", "", "", "", "", "", "", "", ""]])).toBe(0);
    expect(await countCards(model, [["x", "answer", "", "", "", "", "", "", ""]])).toBe(1);
  });

  test('field with only "<br>" or "<div></div>" counts as empty', async () => {
    const model = new Model({
      name: "br-only",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "{{Term}}",
          answerFormat: "{{FrontSide}}",
        },
      ],
    });
    expect(await countCards(model, [["<br>", "", "", "", "", "", "", "", ""]])).toBe(0);
    expect(await countCards(model, [["<div></div>", "", "", "", "", "", "", "", ""]])).toBe(0);
    expect(await countCards(model, [["  ", "", "", "", "", "", "", "", ""]])).toBe(0);
    expect(await countCards(model, [["<div>x</div>", "", "", "", "", "", "", "", ""]])).toBe(1);
  });

  test("{{FrontSide}} alone does not make the question non-empty", async () => {
    // FrontSide is special; it's never in the nonempty_fields set.
    const model = new Model({
      name: "frontside-only",
      fields: FIELDS,
      templates: [
        {
          name: "Card 1",
          questionFormat: "{{FrontSide}}",
          answerFormat: "{{FrontSide}}",
        },
      ],
    });
    expect(await countCards(model, [["x", "y", "", "", "", "", "", "", ""]])).toBe(0);
  });
});
