import { create } from "@bufbuild/protobuf";
import {
  Notetype_ConfigSchema,
  type Notetype_Config,
  Notetype_Config_Kind,
  Notetype_Config_CardRequirementSchema,
  Notetype_Config_CardRequirement_Kind,
  Notetype_Field_ConfigSchema,
  type Notetype_Field_Config,
  Notetype_Template_ConfigSchema,
  type Notetype_Template_Config,
} from "./generated/anki/notetypes_pb";
import { IdGenerator } from "./util/id";
import { DEFAULT_CSS, DEFAULT_LATEX_PRE, DEFAULT_LATEX_POST } from "./util/constants";

const idGen = new IdGenerator();

export interface FieldDef {
  /** Field name (must be unique within the model). */
  name: string;
  /** Keep the field value when adding new notes. @default false */
  sticky?: boolean;
  /** Right-to-left text direction. @default false */
  rtl?: boolean;
  /** Font used in the editor. @default "Arial" */
  fontName?: string;
  /** Font size in the editor. @default 20 */
  fontSize?: number;
  /** Placeholder text shown when the field is empty. @default "" */
  description?: string;
  /** Treat as plain text (no HTML). @default false */
  plainText?: boolean;
}

export interface TemplateDef {
  /** Template name (e.g. "Card 1"). */
  name: string;
  /** HTML template for the question side. Use `{{FieldName}}` for substitutions. */
  questionFormat: string;
  /** HTML template for the answer side. Use `{{FrontSide}}` to include the question. */
  answerFormat: string;
  /** Alternative question template for the browser view. @default "" */
  questionFormatBrowser?: string;
  /** Alternative answer template for the browser view. @default "" */
  answerFormatBrowser?: string;
  /** Font used in the browser column. @default "" */
  browserFontName?: string;
  /** Font size in the browser column. @default 0 */
  browserFontSize?: number;
  /** Override deck for cards generated by this template. @default 0 (use note's deck) */
  targetDeckId?: number;
}

export interface ModelOptions {
  /** Custom model ID. Auto-generated if omitted. */
  id?: number;
  /** Note type name as shown in Anki. */
  name: string;
  /** `"normal"` for standard cards, `"cloze"` for cloze deletions. @default "normal" */
  type?: "normal" | "cloze";
  /** CSS applied to all cards of this note type. */
  css?: string;
  /** Index of the field used for sorting in the browser. @default 0 */
  sortFieldIndex?: number;
  /** Field definitions. Order matters: fields are referenced by index. */
  fields: FieldDef[];
  /** Card templates. Each template generates one card per note (except cloze). */
  templates: TemplateDef[];
  /** LaTeX preamble. @default standard Anki LaTeX preamble */
  latexPre?: string;
  /** LaTeX postamble. @default "\\end{document}" */
  latexPost?: string;
  /** Render LaTeX as SVG instead of PNG. @default false */
  latexSvg?: boolean;
}

/**
 * A note type (model) defining fields and card templates.
 *
 * Use the static constructors for common note types, or create a custom one:
 *
 * @example
 * ```ts
 * // Built-in presets
 * const basic = Model.basic();
 * const reversed = Model.basicAndReversed();
 * const typing = Model.basicTyping();
 * const cloze = Model.cloze();
 *
 * // Custom model
 * const custom = new Model({
 *   name: "Vocab (FR > DE)",
 *   fields: [{ name: "French" }, { name: "German" }],
 *   templates: [{
 *     name: "Card 1",
 *     questionFormat: "{{French}}",
 *     answerFormat: '{{FrontSide}}<hr id="answer">{{German}}',
 *   }],
 * });
 * ```
 */
export class Model {
  readonly id: number;
  readonly name: string;
  readonly type: "normal" | "cloze";
  readonly css: string;
  readonly sortFieldIndex: number;
  readonly fields: FieldDef[];
  readonly templates: TemplateDef[];
  readonly latexPre: string;
  readonly latexPost: string;
  readonly latexSvg: boolean;

  constructor(options: ModelOptions) {
    this.id = options.id ?? idGen.next();
    this.name = options.name;
    this.type = options.type ?? "normal";
    this.css = options.css ?? DEFAULT_CSS;
    this.sortFieldIndex = options.sortFieldIndex ?? 0;
    this.fields = options.fields;
    this.templates = options.templates;
    this.latexPre = options.latexPre ?? DEFAULT_LATEX_PRE;
    this.latexPost = options.latexPost ?? DEFAULT_LATEX_POST;
    this.latexSvg = options.latexSvg ?? false;
  }

  /** Front/Back card type. One card per note. */
  static basic(options?: { name?: string; css?: string }): Model {
    return new Model({
      name: options?.name ?? "Basic",
      css: options?.css,
      fields: [{ name: "Front" }, { name: "Back" }],
      templates: [
        {
          name: "Card 1",
          questionFormat: "{{Front}}",
          answerFormat: '{{FrontSide}}\n\n<hr id="answer">\n\n{{Back}}',
        },
      ],
    });
  }

  /** Front/Back with an additional reversed card. Two cards per note. */
  static basicAndReversed(options?: { name?: string; css?: string }): Model {
    return new Model({
      name: options?.name ?? "Basic (and reversed card)",
      css: options?.css,
      fields: [{ name: "Front" }, { name: "Back" }],
      templates: [
        {
          name: "Card 1",
          questionFormat: "{{Front}}",
          answerFormat: '{{FrontSide}}\n\n<hr id="answer">\n\n{{Back}}',
        },
        {
          name: "Card 2",
          questionFormat: "{{Back}}",
          answerFormat: '{{FrontSide}}\n\n<hr id="answer">\n\n{{Front}}',
        },
      ],
    });
  }

  /** Front/Back where the answer must be typed. Uses Anki's `{{type:Field}}` syntax. */
  static basicTyping(options?: { name?: string; css?: string }): Model {
    return new Model({
      name: options?.name ?? "Basic (type in the answer)",
      css: options?.css,
      fields: [{ name: "Front" }, { name: "Back" }],
      templates: [
        {
          name: "Card 1",
          questionFormat: "{{Front}}\n\n{{type:Back}}",
          answerFormat: '{{Front}}\n\n<hr id="answer">\n\n{{type:Back}}',
        },
      ],
    });
  }

  /** Cloze deletion card type. Use `{{c1::text}}` syntax in the Text field. */
  static cloze(options?: { name?: string; css?: string }): Model {
    return new Model({
      name: options?.name ?? "Cloze",
      type: "cloze",
      css: options?.css ?? `${DEFAULT_CSS}\n\n.cloze {\n  font-weight: bold;\n  color: blue;\n}`,
      fields: [{ name: "Text" }, { name: "Back Extra" }],
      templates: [
        {
          name: "Cloze",
          questionFormat: "{{cloze:Text}}",
          answerFormat: '{{cloze:Text}}\n\n<hr id="answer">\n\n{{Back Extra}}',
        },
      ],
    });
  }

  toNotetypeConfigProtobuf(): Notetype_Config {
    const reqs = this.type === "cloze" ? [] : this.computeRequirements();

    return create(Notetype_ConfigSchema, {
      kind: this.type === "cloze" ? Notetype_Config_Kind.CLOZE : Notetype_Config_Kind.NORMAL,
      sortFieldIdx: this.sortFieldIndex,
      css: this.css,
      latexPre: this.latexPre,
      latexPost: this.latexPost,
      latexSvg: this.latexSvg,
      reqs: reqs.map((req) =>
        create(Notetype_Config_CardRequirementSchema, {
          cardOrd: req.ord,
          kind:
            req.kind === "all"
              ? Notetype_Config_CardRequirement_Kind.ALL
              : Notetype_Config_CardRequirement_Kind.ANY,
          fieldOrds: req.fieldOrds,
        }),
      ),
    });
  }

  toFieldConfigProtobuf(fieldIndex: number): Notetype_Field_Config {
    const field = this.fields[fieldIndex];
    return create(Notetype_Field_ConfigSchema, {
      sticky: field.sticky ?? false,
      rtl: field.rtl ?? false,
      fontName: field.fontName ?? "Arial",
      fontSize: field.fontSize ?? 20,
      description: field.description ?? "",
      plainText: field.plainText ?? false,
    });
  }

  toTemplateConfigProtobuf(templateIndex: number): Notetype_Template_Config {
    const tmpl = this.templates[templateIndex];
    return create(Notetype_Template_ConfigSchema, {
      qFormat: tmpl.questionFormat,
      aFormat: tmpl.answerFormat,
      qFormatBrowser: tmpl.questionFormatBrowser ?? "",
      aFormatBrowser: tmpl.answerFormatBrowser ?? "",
      targetDeckId: BigInt(tmpl.targetDeckId ?? 0),
      browserFontName: tmpl.browserFontName ?? "",
      browserFontSize: tmpl.browserFontSize ?? 0,
    });
  }

  /**
   * Compute card requirements for standard (non-cloze) models.
   * For each template, determine which fields must be non-empty for a card to be generated.
   */
  private computeRequirements(): Array<{ ord: number; kind: "all" | "any"; fieldOrds: number[] }> {
    return this.templates.map((tmpl, ord) => {
      const fieldOrds: number[] = [];
      const fieldPattern = /\{\{(?!FrontSide)(?:type:|#|\/)?([^#/}]+?)\}\}/g;
      let match;

      while ((match = fieldPattern.exec(tmpl.questionFormat)) !== null) {
        const fieldName = match[1].trim();
        const fieldIdx = this.fields.findIndex((f) => f.name === fieldName);
        if (fieldIdx >= 0 && !fieldOrds.includes(fieldIdx)) {
          fieldOrds.push(fieldIdx);
        }
      }

      return {
        ord,
        kind: "any" as const,
        fieldOrds: fieldOrds.length > 0 ? fieldOrds : [0],
      };
    });
  }
}
